# Generated by Django 5.1.3 on 2024-11-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('hire_date', models.DateField()),
                ('job_title', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('salary', models.FloatField()),
                ('manager_id', models.IntegerField(blank=True, null=True)),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
